node /var/www/digitallink_toolkit/server.js 3000 &
node /var/www/digitallink_toolkit/server.js 3001 &
node /var/www/digitallink_toolkit/server.js 3002 &
node /var/www/digitallink_toolkit/server.js 3003 &
node /var/www/digitallink_toolkit/server.js 3004 &
node /var/www/digitallink_toolkit/server.js 3005 &
node /var/www/digitallink_toolkit/server.js 3006 &
node /var/www/digitallink_toolkit/server.js 3007 &
node /var/www/digitallink_toolkit/server.js 3008 &
node /var/www/digitallink_toolkit/server.js 3009 &
